# Stochastic Gradient Descent

In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

import time

import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
class MLR_SGD:
    def __init__(self, learning_rate, epochs):
        self.intercept_ = 0
        self.coef_ = None
        self.lr = learning_rate
        self.epochs = epochs

    def fit_gd(self, X, Y):
        self.coef_ = np.ones(X.shape[1])
        for i in range(self.epochs):
            idx = np.random.randint(0, X.shape[0])
            Y_hat = np.dot(X[idx], self.coef_) + self.intercept_
            intercept_Loss_funct = -2 * (Y[idx] - Y_hat)
            self.intercept_ = self.intercept_ - self.lr * intercept_Loss_funct
            coef_loss_funct = -2 * np.dot((Y[idx] - Y_hat), X[idx])
            self.coef_ = self.coef_ - self.lr * coef_loss_funct
        return self.coef_, self.intercept_

    def predict_gd(self, X):
        Y = np.dot(X, self.coef_) + self.intercept_
        return Y

In [3]:
X, Y = load_diabetes(return_X_y=True)
array_2D = np.hstack((X, Y.reshape(-1, 1)))

df = pd.DataFrame(array_2D)
df

0         1         2         3         4         5         6   \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           7         8         9      10  
0   -0.002592  0.019907 -0.017646  151.0  
1   -0.039493 -0.068332 -0.092204   75.0  
2   -0.002592  0.002861 -0.025930  141.0  
3    0.034309  0.022688 -0.009362  206.0  
4   -0.002592 -0.031988 -0.046641  135.0  
..        ...       ...       ...    ...  
437 -0.002592  0.031193  0.007207  178.0  
438  0.034309 -0.018114  0.044485  104.0  
439 -0.011080 -0.046883  0.015491  132.0  
440  0.026560  0.044529 -0.025930  220.0  
441 -0.039493 -0.004222  0.003064   57.0  

[442 rows x 11 columns]

In [4]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.2, random_state=2)
xtrain, xtest, ytrain, ytest

(array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
         -0.06291688,  0.04034337],
        [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
          0.01703607, -0.0052198 ],
        [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
         -0.09643495, -0.01764613],
        ...,
        [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
          0.08449153, -0.01764613],
        [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
          0.03606033, -0.04249877],
        [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
          0.06898589,  0.12732762]]),
 array([[ 0.06713621, -0.04464164,  0.00349435,  0.03564379,  0.0493413 ,
          0.03125356,  0.07072993, -0.03949338, -0.00061174,  0.01963284],
        [-0.07816532,  0.05068012,  0.07786339,  0.05285804,  0.07823631,
          0.0644473 ,  0.02655027, -0.00259226,  0.04067283, -0.00936191],
        [ 0.04170844,  0.05068012, -0.01482845, -0.01713512, -0.00569682,
 

In [5]:
lr = LinearRegression()

lr.fit(xtrain, ytrain)
Y_pred = lr.predict(xtest)

lr.intercept_, lr.coef_

(151.88331005254167,
 array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]))

In [6]:
r2_score(ytest, Y_pred)

0.4399338661568968

In [7]:
start = time.time()
reg  = MLR_SGD(0.049, 10000)
reg.fit_gd(xtrain, ytrain)
print(f"Time taken by this algorithm is {time.time()-start}")
reg.coef_, reg.intercept_

Time taken by this algorithm is 0.48728203773498535


(array([   8.10576039, -187.09404949,  490.4464894 ,  313.74926295,
         -35.60942391, -116.10847219, -193.23472937,  103.18371228,
         465.44118247,  117.43599991]),
 160.6748548012243)

In [8]:
reg_pred = reg.predict_gd(xtest)
reg_pred.shape, xtest.shape
r2_score(ytest, reg_pred)

0.4423106364481959